---
apiVersion: v1
kind: ConfigMap
metadata:
  name: buckets-config
data:
  bucket-base-name: 'bucket-base-name_replace_me'
  bucket-source: 'xray-source'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-point
data:
  url-external: 'url-external_replace_me'  # No trailing /
  url: 'http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local'  # No trailing /
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-host
data:
  url: xraylabdb
